### ISSUE TITLE
Moquetteライブラリを取り外せませんね

### ISSUE THREAD

**Issue by MihoYamato** [piax/piqt#5]
piaxのpublishおよびsubscribeだけを使いたい時、今の構成(org.piqt.peerパッケージにPeerMqEngineMoquette.javaなどが含まれている)では、moquetteライブラリがないとエラーになりますね。以前は、同じパッケージでもeclipseプロジェクトが分かれていたので、mqtt-on-piaxプロジェクトを使わなければ良かったわけですが、今はきれいにまとめられいるため、分離しにくくなっています。同じパッケージにしたのは自分なのですが、moquetteを取り外して、Paho likeなMqttClientの実装について考えていまして、少し困っています。

**Comment by teranisi** [comment]
ここは基本英語でお願いします．
piax-pubsub と piqt に maven artifact を分けることにしようと思います．

**Comment by teranisi** [comment]
issue-5 branch was opened and merged.
